# Generated by Django 6.0.3 on 2026-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
    ]
